"""The brief forbids baking case-specific knowledge into the prompts.

That is easy to honour on day one and easy to break on day two, when someone "improves"
a prompt by adding a worked example from the corpus in front of them. These tests fail
the build if that happens.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from detective.core.corpus import load_documents
from detective.investigation import prompts
from detective.retrieval import tokenize

#: Every prompt actually sent to a model. Delimiter constants and private fragments are
#: excluded; ``test_every_template_is_exercised`` keeps this in step with the module.
TEMPLATES = {
    name: value
    for name, value in vars(prompts).items()
    if isinstance(value, str) and name.endswith(("_SYSTEM", "_USER"))
}

#: Words shared by any investigative brief; their presence is not corpus leakage.
GENERIC = {
    "the",
    "a",
    "an",
    "and",
    "or",
    "of",
    "to",
    "in",
    "on",
    "for",
    "is",
    "it",
    "that",
    "this",
    "with",
    "from",
    "by",
    "as",
    "at",
    "not",
    "no",
    "be",
    "was",
    "are",
    "you",
    "your",
    "its",
    "one",
    "two",
    "three",
    "four",
    "five",
    "if",
    "than",
    "then",
    "so",
    "but",
    "only",
    "any",
    "all",
    "each",
    "must",
    "may",
    "can",
    "cannot",
    "do",
    "does",
    "did",
    "have",
    "has",
    "had",
    "what",
    "which",
    "when",
    "who",
    "how",
    "why",
    "under",
    "over",
    "before",
    "after",
    "out",
    "up",
    "down",
    "own",
    "same",
    "other",
    "more",
    "most",
    "less",
    "least",
    "very",
    "just",
    "question",
    "questions",
    "answer",
    "answers",
    "search",
    "searches",
    "query",
    "queries",
    "passage",
    "passages",
    "evidence",
    "document",
    "documents",
    "archive",
    "source",
    "sources",
    "report",
    "reports",
    "analyst",
    "investigative",
    "investigation",
    "case",
    "cases",
    "label",
    "labels",
    "quote",
    "quotes",
    "citation",
    "citations",
    "cite",
    "summary",
    "timeline",
    "finding",
    "findings",
    "statement",
    "statements",
    "reason",
    "reasons",
    "relevant",
    "relevance",
    "irrelevance",
    "subject",
    "matter",
    "vocabulary",
    "topical",
    "json",
    "id",
    "string",
    "true",
    "false",
    "empty",
    "list",
    "single",
    "next",
    "turn",
    "still",
    "missing",
    "gap",
    "open",
    "excluded",
    "admit",
    "admitted",
    "admitting",
    "reject",
    "sufficient",
    "verbatim",
    "word",
    "words",
    "outside",
    "knowledge",
    "colleague",
    "act",
    "rule",
    "rules",
    "read",
    "reads",
    "reading",
    "decide",
    "decides",
    "judge",
    "collected",
    "candidate",
    "candidates",
    "already",
    "tried",
    "repeat",
    "chase",
    "issue",
    "specific",
    "unanswered",
    "aspect",
    "concrete",
    "itself",
    "phrasing",
    "settle",
    "support",
    "supports",
    "supported",
    "contradicts",
    "defensible",
    "important",
    "piece",
    "attention",
    "state",
    "states",
    "separate",
    "share",
    "shares",
    "shared",
    "background",
    "similarity",
    "worse",
    "failure",
    "omitting",
    "marginal",
    "bear",
    "bears",
    "bearing",
    "genuinely",
    "retrieved",
    "retrieval",
    "planner",
    "gatekeeper",
    "shown",
    "provided",
    "supplied",
    "carry",
    "rests",
    "points",
    "copy",
    "exact",
    "substring",
    "paraphrase",
    "correct",
    "abbreviate",
    "instead",
    "order",
    "happened",
    "substantive",
    "conclusion",
    "conclusions",
    "directly",
    "sentence",
    "sentences",
    "fill",
    "filling",
    "never",
    "always",
    "write",
    "writing",
    "written",
    "reply",
    "provide",
    "give",
    "given",
    "useful",
    "good",
    "best",
    "per",
    "time",
    "back",
    "come",
    "comes",
    "came",
    "will",
    "would",
    "should",
    "could",
    "there",
    "here",
    "them",
    "they",
    "their",
    "he",
    "she",
    "we",
    "us",
    "our",
    "my",
    "me",
    "i",
    "job",
    "every",
    "both",
    "either",
    "neither",
    "cross",
    "checked",
    "check",
    "known",
    "unknown",
    "point",
    "lists",
    "numbered",
    "target",
    "targets",
    "close",
    "closes",
    "closed",
    "opening",
    "collect",
    "particular",
    "using",
    "use",
    "used",
    "uses",
    "make",
    "makes",
    "made",
    "into",
    "about",
    "above",
    "below",
    "between",
    "during",
    "through",
    "while",
    "where",
    "whether",
    "because",
    "such",
    "like",
    "unless",
    "also",
    "well",
    "way",
    "ways",
    "part",
    "parts",
    "set",
    "sets",
    "new",
    "old",
    "first",
    "last",
    "many",
    "much",
    "few",
    "several",
    "some",
    "none",
    "nothing",
    "something",
    "anything",
    "everything",
    "yet",
    "now",
    "again",
    "once",
    "been",
    "being",
    "name",
    "names",
    "named",
    "naming",
    "rather",
    "entry",
    "entries",
    "line",
    "lines",
    "ending",
    "place",
    "places",
    "placed",
    "marker",
    "markers",
    "range",
    "ranges",
    "narrowest",
    "consecutive",
    "immediately",
    "punctuation",
    "rely",
    "relying",
    "invent",
    "bracketed",
    "locator",
    "locators",
    "run",
}


def corpus_vocabulary(directory: Path) -> set[str]:
    words = {
        token
        for document in load_documents(directory)
        for token in tokenize(document.text)
        if len(token) > 3
    }
    return words - GENERIC


@pytest.mark.parametrize("corpus", ["data", "eval/synthetic"])
def test_prompts_contain_no_corpus_vocabulary(repo_root: Path, corpus: str) -> None:
    """No prompt may mention anything only a reader of the corpus could know."""
    vocabulary = corpus_vocabulary(repo_root / corpus)

    leaked = {name: sorted(set(tokenize(text)) & vocabulary) for name, text in TEMPLATES.items()}
    offenders = {name: words for name, words in leaked.items() if words}

    assert not offenders, f"corpus vocabulary leaked into prompts: {offenders}"


def test_prompts_name_no_entities() -> None:
    """Catches proper nouns that a shared-vocabulary check would miss."""
    banned = re.compile(
        r"\b(bitcoin|solana|ethereum|tornado|crypto|cryptocurrency|wallet|blockchain|"
        r"exchange|hacker|phishing|malware|ransom|warehouse|pallet|badge)\b",
        re.IGNORECASE,
    )

    offenders = {name: banned.findall(text) for name, text in TEMPLATES.items()}

    assert not any(offenders.values()), f"domain entity named in prompts: {offenders}"


def test_every_template_is_exercised() -> None:
    """Guards against a prompt being added but never wired up, and so never checked."""
    assert set(TEMPLATES) == {
        "PLANNER_SYSTEM",
        "PLANNER_USER",
        "ASSESSOR_SYSTEM",
        "ASSESSOR_USER",
        "SYNTHESIS_SYSTEM",
        "SYNTHESIS_USER",
    }
